
bot_contents = [
    {
        "language": "🇷🇺 Русский",
        # "bot_url": "https://t.me/my_django_test_bot",
        # "user_ids": "🗂 Мои ID",
        # "user_ids_cancel": "⬅️ Назад в меню",
        # "increase_chance": "📈 Увеличить шанс",
        # "increase_chance_share": "✅ Поделиться ботом",
        # "channel_join": "Artel matbuot xizmati",
        # "channel_check": "✅ Проверить",
        # "channel_check_success_text": """📌 Поздравляем, вы стали участником конкурса! Ваш ID {}.
# Не потеряйте этот номер.
# Также вы можете увеличить ваш шанс на победу или же ознакомитесь условиями конкурса:""",
#         "channel_check_fail_text": "Пожалуйта подпишитесь на канал для успешной проверки.",
#         "user_ids_text": "У вас есть {} идентификационных номера –",
#         "increase_chance_text": """📌 Чтобы увеличить ваш шанс на победу, вам нужно приобрести как можно больше ID номеров.
# Для этого отправьте приглашение друзьям.
# Когда ваши друзья участвуют в конкурсе по вашему приглашению, вы получаете +1 ID номер для каждого друга.
# Вы можете узнать количество ваших ID номеров в меню.""",
#         "increase_chance_exception_text": "Пожалуйта сначала подпишитесь на канал и нажмите на кнопку ”✅ Проверить”.",
#         "user_ids_exception_text": "Пожалуйта сначала подпишитесь на канал и нажмите на кнопку ”✅ Проверить”.",
        "profile": "📋 Мой профиль",
        "settings": "⚙️ Настройки",
        "settings_language": "🔄 Изменить язык",
        "settings_back_to_menu": "⬅️ Назад в меню",
        "first_name": "📝 Изменить имя",
        "last_name": "📝 Изменить Фамилия",
        "phone_number": "📝 Изменить номер телефона",
        "share_phone_number": "☎️ Поделиться контактом",
        "profile_cancel": "⬅️ Назад в меню",
        "welcome_text": "Добро пожаловать на конкурс пресс-службы Artel!",
        "menu_text": "Меню",
        "first_name_text": "📎 Имя",
        "last_name_text": "📎 Фамилия",
        "phone_number_text": "☎️ Номер телефона",
        "settings_language_text": "✅ Язык успешно обновлен",
        "first_name_helper": "Для удобной обратной связи, пожалуйста введите своё имя:",
        "last_name_helper": "Введите фамилию:",
        "phone_number_helper": "Нажмите на кнопку ”☎️ Поделиться контактом”",
        "profile_cancel_text": "⬅️ Назад в меню",
        "empty_text": "(пусто)",
        "language_choice": "🇷🇺 Русский",
    },
    {
        "language": "🇺🇿 O'zbekcha",
        # "bot_url": "https://t.me/my_django_test_bot",
        # "user_ids": "🗂 Mening IDlarim",
        # "user_ids_cancel": "⬅️ Menyuga qaytish",
        # "increase_chance": "📈 Tanlovda omadni oshirish",
        # "increase_chance_share": "✅ Botni ulashish",
        # "channel_join": "Artel matbuot xizmati",
        # "channel_check": "✅ Tekshirish",
        # "channel_check_success_text": """📌 Tabriklaymiz! Siz tanlovimiz ishtirokchisiga aylandingiz! Ishtirokchi IDingiz {}.
# ID raqamingizni saqlab qo’ying.
# Tanlovda yutish imkoniyatingizni oshiring yoki tanlov shartlari bilan tanishing:""",
#         "channel_check_fail_text": "Tekshiruvdan muvaffaqiyatli o'tish uchun kanalga obuna bo'ling.",
#         "user_ids_text": "Sizda {} ta ID raqami mavjud –",
#         "increase_chance_text": """📌 Tanlovda o’z ID raqamingizni ko’paytirish orqali yutish imkoniyatini oshiring.
# Buning uchun shaxsiy havolangizni do’stlaringizga yuboring.
# Do’stlaringiz taklifingiz orqali tanlovda ishtirok etganida, har bir do’stingiz uchun sizga +1 ta ID raqami beriladi.
# ID raqamlaringiz soni bilan Menyuda tanishishingiz mumkin.""",
#         "increase_chance_exception_text": "Iltimos, avval kanalga obuna bo'ling va ”✅ Tekshirish” tugmasini bosing.",
#         "user_ids_exception_text": "Iltimos, avval kanalga obuna bo'ling va ”✅ Tekshirish” tugmasini bosing.",
        "profile": "📋 Mening profilim",
        "settings": "⚙️ Sozlamalar",
        "settings_language": "🔄 Tilni o'zgartirish",
        "settings_back_to_menu": "⬅️ Menyuga qaytish",
        "first_name": "📝 Ismni o'zgartirish",
        "last_name": "📝 Familiyani o'zgartirish",
        "phone_number": "📝 Telefon raqamini o'zgartirish",
        "share_phone_number": "☎️ Kontaktni ulashish",
        "profile_cancel": "⬅️ Menyuga qaytish",
        "welcome_text": "Artel matbuot xizmati tanlovlariga xush kelibsiz!",
        "menu_text": "Menu",
        "first_name_text": "📎 Ism",
        "last_name_text": "📎 Familiya",
        "phone_number_text": "☎️ Telefon raqami",
        "settings_language_text": "✅ Til muvaffaqiyatli yangilandi",
        "first_name_helper": "Sizga murojaat qilishimiz uchun ismingizni kiriting:",
        "last_name_helper": "Familiyangizni kiriting:",
        "phone_number_helper": "”☎️ Kontaktni ulashish” tugmasini bosing",
        "profile_cancel_text": "⬅️ Menyuga qaytish",
        "empty_text": "(bo'sh)",
        "language_choice": "🇺🇿 O'zbekcha",
    },
]
