
bot_contents = [
    {
        "language": "🇺🇸 English",
        "post_item": "📨 Post your find",
        "post_item_submit": "✍️ Send",
        "post_item_cancel": "❌ Cancel",
        "reject": "❌ Reject",
        "approve": "✅ Approve",
        "block": "🔓 Block",
        "taken": "✅ Taken",
        "item_list": "🗄 Things I found",
        "item_list_cancel": "⬅️ Back to menu",
        "pending_item_list": "📬 List of pending posts",
        "pending_item_list_cancel": "⬅️ Back to menu",
        "active_item_list": "🗂 List of active posts",
        "active_item_list_cancel": "⬅️ Back to menu",
        "profile": "📋 My Profile",
        "settings": "⚙️ Settings",
        "settings_language": "🔄 Change language",
        "settings_back_to_menu": "⬅️ Back to menu",
        "first_name": "📝 Change name",
        "last_name": "📝 Change Last Name",
        "phone_number": "📝 Change phone number",
        "share_phone_number": "☎️ Share contact",
        "profile_cancel": "⬅️ Back to menu",
        "welcome_text": "Welcome to the Lost&Found TTPU bot!",
        "item_list_exception_text": "🔓 You haven't found anything yet",
        "pending_item_list_exception_text": "📌 There are currently no pending posts",
        "active_item_list_exception_text": "📌 No active posts at the moment",
        "item_status_text": "🧷 Current status",
        "item_status_created_text": "📌 Your post is awaiting admin approval",
        "item_status_published_text": "📌 Your post has been published {}",
        "item_status_delivered_text": "📌 The item you found was successfully transferred to the owner",
        "item_title_text": "🖊 Enter the name of what you found",
        "item_location_text": "🖊 State where you found it",
        "item_date_text": "🖊 Enter the date you found it. The date format must be dd-mm-yyyy.",
        "item_date_exception_text": "🖊 Please enter the date correctly. The date format must be dd-mm-yyyy.",
        "item_photo_text": "🖊 Upload a photo of what you found",
        "item_photo_exception_text": "🖊 Upload a simple picture, not a file",
        "item_create_success_text": "✅ Successfully saved",
        "item_create_notification_text": "✉️ You have a new message from @{}",
        "menu_text": "🛎 Menu",
        "first_name_text": "📎 First name",
        "last_name_text": "📎 Last name",
        "phone_number_text": "☎️ Phone number",
        "settings_language_text": "✅ Language successfully updated",
        "first_name_helper": "✏️ Please enter your name:",
        "last_name_helper": "✏️ Enter your last name:",
        "phone_number_helper": "Click on the button ”☎️ Share contact”",
        "profile_cancel_text": "⬅️ Back to menu",
        "empty_text": "(пусто)",
        "language_choice": "🇺🇸 English",
    },
    {
        "language": "🇷🇺 Русский",
        "post_item": "📨 Разместите находку",
        "post_item_submit": "✍️ Отправить",
        "post_item_cancel": "❌ Отменить",
        "reject": "Отклонить",
        "approve": "✅ Одобрить",
        "block": "🔓 Заблокировать",
        "taken": "✅ Взятый",
        "item_list": "🗄 Вещи, которые я нашел",
        "item_list_cancel": "⬅️ Назад в меню",
        "pending_item_list": "📬 Список ожидающих постов",
        "pending_item_list_cancel": "⬅️ Назад в меню",
        "active_item_list": "🗂 Список активных постов",
        "active_item_list_cancel": "⬅️ Назад в меню",
        "profile": "📋 Мой профиль",
        "settings": "⚙️ Настройки",
        "settings_language": "🔄 Изменить язык",
        "settings_back_to_menu": "⬅️ Назад в меню",
        "first_name": "📝 Изменить имя",
        "last_name": "📝 Изменить Фамилия",
        "phone_number": "📝 Изменить номер телефона",
        "share_phone_number": "☎️ Поделиться контактом",
        "profile_cancel": "⬅️ Назад в меню",
        "welcome_text": "Добро пожаловать в бот Lost&Found TTPU!",
        "item_list_exception_text": "🔓 Вы еще ничего не нашли",
        "pending_item_list_exception_text": "📌 На данный момент не имеется ожидающих постов",
        "active_item_list_exception_text": "📌 На данный момент не имеется активных постов",
        "item_status_text": "🧷 Текущий статус",
        "item_status_created_text": "📌 Ваш пост ожидает одобрения администратора",
        "item_status_published_text": "📌 Ваш пост был опубликован {}",
        "item_status_delivered_text": "📌 Вещь который вы нашли успешно был передан владельцу",
        "item_title_text": "🖊 Введите название того, что вы нашли",
        "item_location_text": "🖊 Укажите, где вы его нашли",
        "item_date_text": "🖊 Введите дату, когда вы его нашли. Формат даты должен быть дд-мм-гггг.",
        "item_date_exception_text": "🖊 Пожалуйста, вводите дату правильно. Формат даты должен быть дд-мм-гггг.",
        "item_photo_text": "🖊 Загрузите фото того, что вы нашли",
        "item_photo_exception_text": "🖊 Загрузите простую картинку, а не файл",
        "item_create_success_text": "✅ Успешно сохранено",
        "item_create_notification_text": "✉️ У вас есть новое сообщение от пользователя @{}",
        "menu_text": "🛎 Меню",
        "first_name_text": "📎 Имя",
        "last_name_text": "📎 Фамилия",
        "phone_number_text": "☎️ Номер телефона",
        "settings_language_text": "✅ Язык успешно обновлен",
        "first_name_helper": "✏️ Пожалуйста введите своё имя:",
        "last_name_helper": "✏️  Введите фамилию:",
        "phone_number_helper": "Нажмите на кнопку ”☎️ Поделиться контактом”",
        "profile_cancel_text": "⬅️ Назад в меню",
        "empty_text": "(пусто)",
        "language_choice": "🇷🇺 Русский",
    },
    {
        "language": "🇺🇿 O'zbekcha",
        "post_item": "📨 Topilmani joylash",
        "post_item_submit": "✍️ Yuborish",
        "post_item_cancel": "❌ Bekor qilish",
        "reject": "❌ Rad etish",
        "approve": "✅ Tasdiqlash",
        "block": "🔓 Bloklash",
        "taken": "✅ Olingan",
        "item_list": "🗄 Men topkan narsalar",
        "item_list_cancel": "⬅️ Menyuga qaytish",
        "pending_item_list": "📬 Kutilayotgan postlar ro'yxati",
        "pending_item_list_cancel": "⬅️ Menyuga qaytish",
        "active_item_list": "🗂 Faol postlar ro'yxati",
        "active_item_list_cancel": "⬅️ Menyuga qaytish",
        "profile": "📋 Mening profilim",
        "settings": "⚙️ Sozlamalar",
        "settings_language": "🔄 Tilni o'zgartirish",
        "settings_back_to_menu": "⬅️ Menyuga qaytish",
        "first_name": "📝 Ismni o'zgartirish",
        "last_name": "📝 Familiyani o'zgartirish",
        "phone_number": "📝 Telefon raqamini o'zgartirish",
        "share_phone_number": "☎️ Kontaktni ulashish",
        "profile_cancel": "⬅️ Menyuga qaytish",
        "welcome_text": "Lost&Found TTPU botiga xush kelibsiz!",
        "item_list_exception_text": "🔓 Siz hali hech narsa topmadingiz",
        "pending_item_list_exception_text": "📌Hozirda kutilayotgan postlar yo‘q",
        "active_item_list_exception_text": "📌Hozirda faol postlar mavjud emas",
        "item_status_text": "🧷 Hozirgi status",
        "item_status_created_text": "📌 Sizning postingiz administrator tomonidan tasdiqlanishini kutilmoqda",
        "item_status_published_text": "📌 Sizning postingiz kanalga joylandi {}",
        "item_status_delivered_text": "📌 Siz topgan narsa egasiga muvaffaqiyatli topshirildi",
        "item_title_text": "🖊 Topkan narsangizni nomini kiriting",
        "item_location_text": "🖊 Qayerdan topkaningizni kiriting",
        "item_date_text": "🖊 Qachon topkaningizni sanasini kiriting. Sana formati dd-mm-yyyy bo'lishi kerak.",
        "item_date_exception_text": "🖊 Iltimos, sanani to'g'ri kiriting. Sana formati formati dd-mm-yyyy bo'lishi kerak.",
        "item_photo_text": "🖊 Topkan narsangizni suratini yuklang",
        "item_photo_exception_text": "🖊 Iltimos oddiy rasim tashlang fayl qilib emas",
        "item_create_success_text": "✅ Muvaffaqiyatli saqlandi",
        "item_create_notification_text": "✉️ Sizga @{} dan yangi xabar keldi",
        "menu_text": "🛎 Menu",
        "first_name_text": "📎 Ism",
        "last_name_text": "📎 Familiya",
        "phone_number_text": "☎️ Telefon raqami",
        "settings_language_text": "✅ Til muvaffaqiyatli yangilandi",
        "first_name_helper": "✏️ Iltimos ismingizni kiriting:",
        "last_name_helper": "✏️ Familiyangizni kiriting:",
        "phone_number_helper": "”☎️ Kontaktni ulashish” tugmasini bosing",
        "profile_cancel_text": "⬅️ Menyuga qaytish",
        "empty_text": "(bo'sh)",
        "language_choice": "🇺🇿 O'zbekcha",
    },
]
