# Generated by Django 4.1.1 on 2022-10-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='item_photo_exception_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
