# Generated by Django 4.1.1 on 2022-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Published'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Blocked')], default=1),
        ),
    ]
