# Generated by Django 4.1.1 on 2022-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botcontent_item_create_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
